module.exports = [
    {
        img:"https://storage.googleapis.com/golden-wind/bootcamp-launchbase/assets/starter.svg",
        name:"starter",
        animal:"Iniciante",
        cor:"das"
    },
    {
        img:"https://storage.googleapis.com/golden-wind/bootcamp-launchbase/assets/launchbase.svg",
        name:"launchbase",
        animal:"Intermediário",
        cor:"das"
    },
    {
        img:"https://storage.googleapis.com/golden-wind/bootcamp-launchbase/assets/gostack.svg",
        name:"gostack",
        animal:"Avançado",
        cor:"das"
    }
]